# Generated by Django 2.0.2 on 2018-06-20 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datereq', models.DateTimeField(auto_now=True, verbose_name='Дата, время добавления записи')),
                ('idreq', models.CharField(max_length=100, null=True, verbose_name='Идентификатор запроса')),
                ('service', models.CharField(max_length=50, verbose_name='Наименование сервиса')),
                ('method', models.CharField(max_length=50, verbose_name='Наименованеи метода')),
                ('code', models.CharField(choices=[('01', 'Запрашиваемые сведения не найдены'), ('51', 'Запрос принят в обработку'), ('52', 'Ответ не готов'), ('53', 'Сведения не могут быть предоставлены в электронном виде'), ('82', 'Ошибка форматно-логического контроля'), ('83', 'Отсутсвует запрос с указанным идентификатором и видом запрошенных сведений'), ('97', 'Ошибка сохранения файла'), ('98', 'Ошибка проверки подписи сообщения'), ('99', 'Системная ошибка')], max_length=2, null=True, verbose_name='Код возврата')),
                ('notsignfilename', models.CharField(max_length=100, null=True, verbose_name='Имя первоначально сгенерированного файла')),
                ('reqfilename', models.CharField(max_length=100, null=True, verbose_name='Имя файла, содержащего запрос')),
                ('resfilename', models.CharField(max_length=100, null=True, verbose_name='Имя файла, содержащего ответ')),
                ('params', models.CharField(max_length=250, null=True, verbose_name='Параметры запроса')),
                ('dateres', models.DateTimeField(null=True, verbose_name='Дата, время добавления ответа')),
                ('root_id', models.UUIDField(default=uuid.uuid4, null=True, verbose_name='Идентификатор первой задачи в цепочке')),
                ('this_id', models.UUIDField(default=uuid.uuid4, null=True, verbose_name='Идентификатор выполняемой задачи, саздашей запись в БД')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['datereq'],
            },
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['idreq', 'root_id', 'this_id', 'method'], name='celeryApp_r_idreq_e93ae5_idx'),
        ),
    ]
