# Generated by Django 2.0.2 on 2020-02-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fns', '0002_auto_20180620_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='файл',
            name='size',
            field=models.IntegerField(null=True, verbose_name='Размер файла'),
        ),
    ]
